name: type_parser
description: A powerful and flexible Dart package for parsing and converting dynamic values to various types, including primitives, lists, and maps. It provides both safe (tryParse) and explicit (parse) methods for robust type handling.
version: 0.0.1
homepage: https://github.com/venhdev/type_parser
repository: https://github.com/venhdev/type_parser

environment:
  sdk: ">=2.17.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
