name: type_parser
description: A powerful Dart package for parsing and converting dynamic values to various types. Provides safe (tryParse) and explicit (parse) methods.
version: 0.0.2
homepage: https://github.com/venhdev/type_parser
repository: https://github.com/venhdev/type_parser

environment:
  sdk: ">=2.17.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
